### PR TITLE
Catch error if no albumart found.

### PR DESCRIPTION
**Pull request by stonega**
Fix the bug, load file failed when no album art included in audio file.

### CODE REVIEW

**Comment by alexmercerind** [comment]
Thanks!

I had to do this some day, either now or in future.

I appreciate the PR.

**Comment by alexmercerind** [comment]
I'll make changes in Java implementation itself to avoid try catch clause in future.

**Comment by stonega** [comment]
Thank you for the plugin, I have used it in my project :)

**Comment by stonega** [comment]
@alexmercerind Yeah, that would be great!

**Comment by alexmercerind** [comment]
@stonega.

Just so that you know, now this package has name `flutter_media_metadata` to specify its functionality more clearly.

It also has Linux support now.
Windows support will arrive soon.

**Comment by stonega** [comment]
@alexmercerind Great job!

**Pull request merged**
